run:
  timezone: "America/Sao_Paulo"

paths:
  output_dir: ../corrprev-ct2w15-adjustment/outputs

output:
  timestamp_timezone: "UTC"

temperature:
  round_model_before_correction: true
  model_round_decimals: 1
  output_rounding: python
  output_round_decimals: 1

rain:
  output_rounding: python
  output_round_decimals: 1

processing:
  forecast_hours: 72
  netcdf_extra_hours: 3
